### ISSUE TITLE
time issue in couchdb retrieve_weather

### ISSUE THREAD

**Issue by joydisee** [joydisee/Homza#14]
'''
pi@raspberrypi ~/Homza $ sudo python whos_up.py
Traceback (most recent call last):
  File "whos_up.py", line 2, in <module>
    from couchdb_handler import *
  File "/home/pi/Homza/couchdb_handler.py", line 367, in <module>
    retrieve_time_weather()
  File "/home/pi/Homza/couchdb_handler.py", line 311, in retrieve_time_weather
    seconds_since_last_weather = time.mktime(time.localtime()) - time.mktime(time.strptime(str(row.value['time']), "%Y-%m-%d %H:%M:%S"))
KeyError: 'time'
pi@raspberrypi ~/Homza $ python init_users.py
Traceback (most recent call last):
  File "init_users.py", line 2, in <module>
    from couchdb_handler import *
  File "/home/pi/Homza/couchdb_handler.py", line 367, in <module>
    retrieve_time_weather()
  File "/home/pi/Homza/couchdb_handler.py", line 311, in retrieve_time_weather
    seconds_since_last_weather = time.mktime(time.localtime()) - time.mktime(time.strptime(str(row.value['time']), "%Y-%m-%d %H:%M:%S"))
KeyError: 'time'
'''

@Lussylver :flags:

**Comment by Lussylver** [comment]
fixed
